### ISSUE TITLE
ERROR: Cannot use "await" as an identifier here

### ISSUE THREAD

**Issue by sneakylenny** [hash-bang/async-chainable#3]
I got this code:

```js
import asyncChainable from 'async-chainable'

asyncChainable()
    .then((next) => {
      console.log('first')
      next()
    })
    .then((next) => {
      console.log('second')
      next()
    })
    .start()
```

But when I compile it I get error:

```
11:33:13 [vite] hmr update /src/views/HomeView.vue
X [ERROR] Cannot use "await" as an identifier here:

    node_modules/.pnpm/async-chainable@2.6.1/node_modules/async-chainable/index.js:372:9:
      372 │ function await() {
          ╵          ~~~~~

11:33:16 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/async-chainable@2.6.1/node_modules/async-chainable/index.js:372:9: ERROR: Cannot use "await" as an identifier here:
    at failureErrorWithLog (C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604:15)
    at C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1056:28
    at runOnEndCallbacks (C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1476:61)  
    at buildResponseToResult (C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1054:7)
    at C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1166:14
    at responseCallbacks.<computed> (C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (C:\Users\username\Documents\GitHub\project\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
```

I use:

```
Node: v19.6.0
Vite: 4.0.0 win32-x64
```

**Comment by hash-bang** [comment]
Ah nasty. Seems that `await` is now a reserved word when naming functions.

I've corrected the code to `wait()` internally but can still be queued with `.await()`.

Fixed in `v2.6.2`
